version : '2'
services:
 redis:
  image: redis

 db:
  image: postgres:9.4

 vote:
  image: docker/example-voting-app-vote
  ports:
  - 5000:80
  depends_on:
   - redis

 result:
  image: docker/example-voting-app-result
  ports:
  - 5001:80
  depends_on: 
   - db

 worker:
  image: docker/example-voting-app-worker
  depends_on:
   - redis
   - db
