version: '2'
services:
 radis:
  image: redis
  networks:
    - back-end
  volumes:
   - radis-data:/var/lib/redis

 db:
  image: postgres:9.4
  networks:
    - back-ned
  volumes:
   - db-data:/var/lib/postgresql/data 

 vote:
  image: voting-app
  networks:
    - front-end
    - back-end

 result:
  image: result
  networks:
    - front-end
    - back-end



networks:
  front-end:
    driver: bridge
  back-end:
    driver: bridge

volumes:
  redis-data:
  db-data:

